# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_time', models.TimeField(verbose_name='Time spent on this project')),
                ('rec_date', models.DateField(verbose_name='Date this project was worked on')),
                ('project', models.CharField(choices=[('YT', 'Watching Youtube'), ('FB', 'Checking Facebook'), ('PR', 'Pretending to work'), ('SM', 'Smoke break')], default='PR', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
